version: '3.1'

services:
    puppeteer-node:
        image: puppeteer-node
        build: ./
        env_file: .env
        depends_on:
            - "chrome"
    chrome:
        build:
            context: chrome/
        ports:
            - 9222:9222